### ISSUE TITLE
Activator.cmd file is not running on Windows

### ISSUE THREAD

**Issue by Tariqali99** [khaouitiabdelhakim/Microsoft-Office-With-Activation-For-Lifetime#1]
I am getting this below error while running this Activator.cmd file on windows

"Error: Script either has LF line ending issue, or it failed to read itself."

**Comment by khaouitiabdelhakim** [comment]
Hi @Tariqali99, I have fixed it, try using the Activator.cmd inside the Activator.rar after unzipping it. The issue was related to text changed by github not me! help it'll work.
![Capture](https://github.com/khaouitiabdelhakim/Microsoft-Office-With-Activation-For-Lifetime/assets/115430366/cbfe7fef-72f6-4fc6-aff5-19591dc6761d)
